server:
  port: 9001

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: adminuser
    url: jdbc:mysql://localhost:3306/carefirst
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true